name: Update weather Excel

on:
  schedule:
    - cron: "0 1 * * *"   # every day at 06:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script
        run: python update_weather.py

      - name: Save updated Excel
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add results.xlsx
          git commit -m "Update weather data" || echo "No changes"
          git push
